org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Loaders Properties
minecraft_version=26.2
loader_version=0.19.5
neo_version=26.2.0.85

# Mod Properties
mod_version=1.0.0
mod_id=thunder_detector
group=starman.thunder.detect

# Dependencies
fabric_api_version=0.160.0+26.2
