org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Loaders Properties
loader_version=0.19.5
neo_version=26.1.2.109

# Mod Properties
mod_version=1.0.1
mod_id=thunder_detector
group=starman.thunder_detector
minecraft_display_version=26.x

# Dependencies
minecraft_version=26.1.2
fabric_api_version=0.155.3+26.1.2
