modLoader = "javafml"
loaderVersion = "26.2.0.85"
license = "MIT"

[[mods]]
modId = "thunder_detector"
version = "${mod_version}"
displayName = "Thunder Detector"
description = "When a thunder starts, the mod opens a new window with information about it!"
authors = "Starman"
iconFile = "assets/thunder_detector/icon.png"
bannerFile = "assets/thunder_detector/icon.png"

displayURL = "https://modrinth.com/project/thunder-detector"
issueTrackerURL = "https://github.com/StarmanMine142/thunder_detector/issues"

[[dependencies.thunder_detector]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thunder_detector]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.85,)"
ordering = "NONE"
side = "BOTH"